services:
  - type: web
    name: autosalon-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_VERSION
        value: 22.22.0
      - key: PORT
        value: 5000
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BCRYPT_ROUNDS
        value: 12

databases:
  - name: autosalon-db
    databaseName: auto_store
    user: auto_store_user
